#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def getTotalX(a, b):
    cnt = 0
    for i in range(1, 101):
        works = True
        for j in a:
            if i % j != 0:
                works = False
        for j in b:
            if j % i != 0:
                works = False
        if works:
            cnt += 1

    return cnt

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()
