#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the circularArrayRotation function below.
def circularArrayRotation(a, k, queries):
    arr=[0]*len(a)
    arr1=[0]*len(queries)
    for i in range(0,len(a)):
        pos=i+1
        pos=pos+k    
        if(len(a)>=pos):
            arr[pos-1]=a[i]
        if(len(a)<pos):
            arr[(pos%len(a))-1]=a[i]
    l=0
    while(l<len(queries)):
        for i in queries:
            arr1[l]=arr[i]
            l+=1
    return(arr1)        
    


        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nkq = input().split()

    n = int(nkq[0])

    k = int(nkq[1])

    q = int(nkq[2])

    a = list(map(int, input().rstrip().split()))

    queries = []

    for _ in range(q):
        queries_item = int(input())
        queries.append(queries_item)

    result = circularArrayRotation(a, k, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
