#!/bin/python

import math
import os
import random
import re
import sys

# Complete the gameOfThrones function below.
def gameOfThrones(s):
    sl=list(s)
    empty_list=list()
    count_odd=0
    
    for i in s:
        if i not in empty_list:
            empty_list.append(i)
    for i in empty_list:
        if(sl.count(i)%2!=0):
            count_odd+=1
    if(count_odd<=1):
        return('YES')
    return('NO')

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = raw_input()

    result = gameOfThrones(s)

    fptr.write(result + '\n')

    fptr.close()
