#!/bin/python

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c):
    win=0
    count=0
    i=0
    while(i<(len(c))):
        if(i<len(c)-2 and c[i+2]==0 and i!=len(c)-1):
            i+=1
        if(i!=len(c)-1):
            count+=1    
        i+=1
    return (count)        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input())

    c = map(int, raw_input().rstrip().split())

    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
