#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c, k):
    e=100
    damage=0
    i=1
    j=0
    no_of_steps=(len(c)-1)//k
    while(i<=no_of_steps):
        if(c[j+k]==0):
            damage+=1
        if(c[j+k]==1):
            damage+=3
        i+=1
        j+=k
    if(c[0]==1):
        return (e-damage-1-2)
    else:
        return(e-damage-1)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c, k)

    fptr.write(str(result) + '\n')

    fptr.close()
