#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the workbook function below.
def workbook(n, k, arr):
    total_pages = 1
    special_pages = 0
    for i in range(0,len(arr)):
        count = 0
        for j in range(1,arr[i]+1):
            if(j==total_pages):
                special_pages+=1
            count+=1
            if(count==k or j==arr[i]):
                total_pages+=1
                count=0

    return special_pages



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    arr = list(map(int, input().rstrip().split()))

    result = workbook(n, k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
