#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the makingAnagrams function below.
def makingAnagrams(s1, s2):
    common_elements=0
    ss2=list(s2)
    for i in s1:
        if i in ss2:
            ss2.remove(i)
            common_elements+=1
    
    return(len(s1)+len(s2)-(2*common_elements))    
    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = makingAnagrams(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
