#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the migratoryBirds function below.
def migratoryBirds(arr):
    one = arr.count(1)
    two = arr.count(2)
    three = arr.count(3)
    four = arr.count(4)
    five = arr.count(5)
    li=[one,two,three,four,five]
    return(1+li.index(max(li)))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
