#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumSwaps function below.
def minimumSwaps(arr):
    a=arr
    sort=sorted(arr)
    a_rev=reversed(arr)
    d={}
    for i in range(n):
        d[sort[i]]=i
    swaps=0
    i=0
    while i<n:
        if(sort[i]==a[i]):
            i+=1
            continue
        swaps+=1
        a[d[a[i]]],a[i]=a[i],a[d[a[i]]]
        
    return swaps             
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    res = minimumSwaps(arr)

    fptr.write(str(res) + '\n')

    fptr.close()
