#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    arr=[]
    counts=[]
    for i in a:
        if i not in arr:
            arr.append(i)
    arr.sort()
    if(len(arr)==1):
        return (len(a))

    for i in arr:
        counts.append(a.count(i))


    for i in range(0,len(arr)-1):
        if(abs(arr[i+1]-arr[i])<=1):
            counts.append(a.count(arr[i])+a.count(arr[i+1]))

   
    return (max(counts))        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
