#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the poisonousPlants function below.
def poisonousPlants(p):
    arr=p
    bol=True
    day=0
    while(bol):
        ls=[]
        a=len(arr)
        for i in range(1,len(arr)):
            if(arr[i]<arr[i-1]):
                ls.append(arr[i-1])
                    
            if(i==a-1):
                if(arr[i]<arr[i-1]):
                    ls.append(arr[i])
                   
        if(len(ls)==a):
            bol=False
        if(len(ls)!=a):
            day+=1
            arr=ls
    return day        

        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = poisonousPlants(p)

    fptr.write(str(result) + '\n')

    fptr.close()
