#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    ar=[0]*(n+1)
    ar[0]=0
    ar[1]=2
    shared=5
    liked=0

    for i in range(1,n+1):
        liked=shared//2
        ar[i]=liked+ar[i-1]
        shared=liked*3
    return ar[n]    



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
